# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/184aa754-b22a-4b10-9223-a73983e29b40";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b0b4a2bf-12e4-4e62-985a-f48f722c3789".device = "/dev/disk/by-uuid/b0b4a2bf-12e4-4e62-985a-f48f722c3789";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/872B-8046";
      fsType = "vfat";
    };

  fileSystems."/nas/services" =
    {
      device = "taskpool/services";
      fsType = "zfs";
    };

  fileSystems."/nas/media" =
    {
      device = "taskpool/media";
      fsType = "zfs";
    };

  fileSystems."/nas/photos" =
    {
      device = "taskpool/photos";
      fsType = "zfs";
    };

  fileSystems."/nas/junk" =
    {
      device = "taskpool/junk";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f5fb7d30-593f-48e5-a0a4-3a7ed3607978"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
